Fix "rpm: generate tarball from checked out sources"
This fixes commit 8c72ab9c088a5ee038e57a1907c3882788a84cd6.

Fixes:

	Run rpmdev-setuptree
	warning: Downloading https://github.com/gportay/github-workflows/archive/v10.tar.gz to /github/home/rpmbuild/SOURCES/v10.tar.gz
	curl: (22) The requested URL returned error: 404
	error: Executing url helper "/usr/bin/curl   --silent --show-error --fail --globoff --location -o /github/home/rpmbuild/SOURCES/v10.tar.gz https://github.com/gportay/github-workflows/archive/v10.tar.gz" failed with status 22
	error: Couldn't download https://github.com/gportay/github-workflows/archive/v10.tar.gz
	Error: Process completed with exit code 1.