deb: use debian:trixie image
Important: The created wrapper script /usr/local/bin/gpg is not run by
dpkg-buildpackage[1] since trixie (dpkg 1.22.21). PATH contains
/usr/local/bin, dpkg-buildpackage runs /usr/bin/gpg, and it ends with
the error attached below. This diverts original binary gpg to gpg.real
and move wrapper script /usr/local/bin/gpg to /usr/bin/gpg to ensure
dpkg-buildpackage runs the wrapper script.

	dpkg-buildpackage: info: full upload; Debian-native package (full source is included)

	  Error: Failed to sign
	because: Error: Operation failed: Inappropriate ioctl for device <Pinentry>

Note: Alternatively, the dpkg-buildpackage works fine if the options
--sign-command=/usr/local/bin/gpg[2] and --sign-backend=gpg[3] are set.

	dpkg-buildpackage --force-sign --sign-keyid="${{ vars.PGP_KEY_NAME }}" --sign-command=/usr/local/bin/gpg --sign-backend=gpg

[1]: https://manpages.debian.org/trixie/dpkg-dev/dpkg-buildpackage.1.en.html
[2]: https://manpages.debian.org/trixie/dpkg-dev/dpkg-buildpackage.1.en.html#p
[3]: https://manpages.debian.org/trixie/dpkg-dev/dpkg-buildpackage.1.en.html#sign~2